name: Run CI

on:
  push:
    branches:
    - '**'

jobs:
  main:
    runs-on: ubuntu-latest

    # Elasticsearch
    services:
      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl localhost:9200"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Preparing to build
      run: |
        echo Running on branch ${GITHUB_REF##*/}
        mkdir /tmp/build

    # Build
    - name: Build Harvest
      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 harvest ${GITHUB_REF##*/}

    - name: Build Registry Manager
      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 manager master

    - name: Build API
      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 api master

    # Start API server
    - name: Start API server
      run: >-
        docker run --rm --name api --detach --network ${{ job.container.network }}
        -p 8080:8080 -v /tmp/build:/build tdddblog/pds_api_server:1.0
    
    # Load test data
    - name: Load Test Data
      run: >-
        docker run --rm --name registry-load --network ${{ job.container.network }}
        -e "ES_URL=http://elastic:9200" -v /tmp/build:/build tdddblog/pds_load_test_data:1.0

    - name: Wait for Elasticsearch to commit data
      run: sleep 5

    # Run tests
    - name: Test Elasticsearch
      run: curl "localhost:9200/registry/_search?q=*&_source=false&pretty"

    - name: Test API server
      run: >-
        docker run --rm --name=newman --network ${{ job.container.network }}
        -v /tmp/build/postman:/etc/newman postman/newman:latest run postman_collection.json 
